# Generated by Django 4.1.7 on 2023-03-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='studentID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='writer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
